Resources:
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: TempControlFunction
      Handler: app.lambda_handler
      Runtime: python3.9
      Code:
        S3Bucket: your-code-bucket
        S3Key: lambda-code.zip
      Role: arn:aws:lambda:us-east-1:982534387133:function:TempControlFunction

  ApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: EnergyOptimizationAPI

  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: smart-building-dashboard
